name: Release new version
run-name: Release new version
on:
  push:
    branches:
      - 'main'
      - 'test'
jobs:
  change_ver:
    name: Change version
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Change version
        id: change_ver
        shell: powershell
        run: |
          $fileName = "Properties\AssemblyInfo.cs"
          $data = Get-Content $fileName
          $newVersion = [int]$data[12].Substring(30,3)+1
          $data[12] = "[assembly: AssemblyVersion(`"1.$newVersion.0.0`")]"
          $data[13] = "[assembly: AssemblyFileVersion(`"1.$newVersion.0.0`")]"
          Set-Content $fileName $data
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: AssemblyInfo
          path: Properties/AssemblyInfo.cs

  build_manual_update:
    name: Build FallGuysStatsManualUpdate.zip
    runs-on: windows-latest
    needs: change_ver
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: AssemblyInfo
          path: Properties
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build
        run: msbuild /t:build /p:configuration=Release /p:platform="Any CPU"
      - name: Compress artifacts
        shell: powershell
        run: Compress-Archive -Path bin\* -DestinationPath FallGuysStatsManualUpdate.zip -Update
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: FallGuysStatsManualUpdate
          path: FallGuysStatsManualUpdate.zip

  build:
    name: Build FallGuysStats.zip
    runs-on: windows-latest
    needs: change_ver
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: AssemblyInfo
          path: Properties
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build
        run: msbuild /t:build /p:configuration=ReleaseUpdate /p:platform="Any CPU"
      - name: Compress artifacts
        shell: powershell
        run: Compress-Archive -Path bin\* -DestinationPath FallGuysStats.zip -Update
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: FallGuysStats
          path: FallGuysStats.zip
  commit:
    name: Commit Files
    runs-on: windows-latest
    outputs:
      version: ${{ steps.checkver.outputs.VERSION }}
    needs: [build_manual_update, build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Artifacts AssemblyInfo
        uses: actions/download-artifact@v3
        with:
          name: AssemblyInfo
          path: Properties
      - name: Download Artifacts FallGuysStatsManualUpdate
        uses: actions/download-artifact@v3
        with:
          name: FallGuysStatsManualUpdate
      - name: Download Artifacts FallGuysStats
        uses: actions/download-artifact@v3
        with:
          name: FallGuysStats
      - name: Check version
        id: checkver
        shell: powershell
        run: |
          $fileName = "Properties\AssemblyInfo.cs"
          $data = Get-Content $fileName
          $output = "::set-output name=version::"+$data[12].Substring(30,3)
          echo $output
      - name: Commit changes
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add Properties/AssemblyInfo.cs
          git add FallGuysStats.zip
          git add FallGuysStatsManualUpdate.zip
          git commit -m "Version 1.${{steps.checkver.outputs.version}} Update" -a
          echo "::set-output name=push::true"
        shell: bash
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: test
  release:
    name: Release
    runs-on: windows-latest
    needs: commit
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Artifacts AssemblyInfo
        uses: actions/download-artifact@v3
        with:
          name: AssemblyInfo
          path: Properties
      - name: Download Artifacts FallGuysStatsManualUpdate
        uses: actions/download-artifact@v3
        with:
          name: FallGuysStatsManualUpdate
      - name: Download Artifacts FallGuysStats
        uses: actions/download-artifact@v3
        with:
          name: FallGuysStats
      - name: Check version
        id: checkver
        shell: powershell
        run: |
          $fileName = "Properties\AssemblyInfo.cs"
          $data = Get-Content $fileName
          $output = "::set-output name=version::"+$data[12].Substring(30,3)
          echo $output
      - name: Release build
        uses: "softprops/action-gh-release@v1"
        with:
          name: "Release v1.${{steps.checkver.outputs.version}}"
          tag_name: "v1.${{steps.checkver.outputs.version}}.0"
          prerelease: false
          body: |
            This release was triggered by commit ${{ env.GITHUB_SHA }} and released automatically.
          files: |
            FallGuysStats.zip
            FallGuysStatsManualUpdate.zip
