name: Release new version
run-name: Release new version
on:
  push:
    branches:
      - 'main'
      - 'test'
jobs:
  update:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Change version
        shell: powershell
        run: |
          $fileName = "Properties\AssemblyInfo.cs"
          $data = Get-Content $fileName
          $newVersion = [int]$data[12].Substring(30,3)+1
          $data[12] = "[assembly: AssemblyVersion(`"1."+$newVersion+".0.0`")]"
          $data[13] = "[assembly: AssemblyFileVersion(`"1."+$newVersion+".0.0`")]"
          Set-Content $fileName $data
          echo "new_version="+$newVersion >> $GITHUB_ENV
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build (FallGuysStatsManualUpdate)
        run: msbuild /t:build /p:configuration=Release /p:platform="Any CPU"
      - name: Compress artifacts (FallGuysStatsManualUpdate)
        shell: powershell
        run: Compress-Archive -Path bin\* -DestinationPath FallGuysStatsManualUpdate.zip
      - name: Clean artifacts (FallGuysStatsManualUpdate)
        shell: powershell
        run: Remove-Item -Path bin -Recurse
      - name: Build
        run: msbuild /t:build /p:configuration=ReleaseUpdate /p:platform="Any CPU"
      - name: Compress artifacts
        shell: powershell
        run: Compress-Archive -Path bin\* -DestinationPath FallGuysStats.zip
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build_artifacts
          path: |
            FallGuysStats.zip
            FallGuysStatsManualUpdate.zip
      - name: Commit changes
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add Properties/AssemblyInfo.cs
          git add FallGuysStats.zip
          git add FallGuysStatsManualUpdate.zip
          git commit -m "Version 1.${{ env.new_version }} Update" -a
          echo "::set-output name=push::true"
        shell: bash
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release build
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v1.${{ env.new_version }}.0"
          prerelease: false
          title: "Release v1.${{ env.new_version }}"
          files: |
            FallGuysStats.zip
            FallGuysStatsManualUpdate.zip
