name: Release new version
run-name: Release new version
on:
  push:
    branches:
      - 'main'
      - 'test'
jobs:
  change_ver:
    name: Change version
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Change version
        id: change_ver
        shell: powershell
        run: |
          $fileName = "Properties\AssemblyInfo.cs"
          $data = Get-Content $fileName
          $newVersion = [int]$data[12].Substring(30,3)+1
          $data[12] = "[assembly: AssemblyVersion(`"1."+$newVersion+".0.0`")]"
          $data[13] = "[assembly: AssemblyFileVersion(`"1."+$newVersion+".0.0`")]"
          Set-Content $fileName $data
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: AssemblyInfo
          path: Properties/AssemblyInfo.cs

  build_manual_update:
    name: Build FallGuysStatsManualUpdate.zip
    runs-on: windows-latest
    needs: change_ver
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: AssemblyInfo
          path: Properties
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build
        run: msbuild /t:build /p:configuration=Release /p:platform="Any CPU"
      - name: Compress artifacts
        shell: powershell
        run: Compress-Archive -Path bin\* -DestinationPath FallGuysStatsManualUpdate.zip -Update
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: FallGuysStatsManualUpdate
          path: FallGuysStatsManualUpdate.zip

  build:
    name: Build FallGuysStats.zip
    runs-on: windows-latest
    needs: change_ver
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: AssemblyInfo
          path: Properties
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build
        run: msbuild /t:build /p:configuration=ReleaseUpdate /p:platform="Any CPU"
      - name: Compress artifacts
        shell: powershell
        run: Compress-Archive -Path bin\* -DestinationPath FallGuysStats.zip -Update
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: FallGuysStats
          path: FallGuysStats.zip
  commit:
    name: Commit and release
    runs-on: windows-latest
    needs: [change_ver, build_manual_update, build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Artifacts AssemblyInfo
        uses: actions/download-artifact@v3
        with:
          name: AssemblyInfo
          path: Properties
      - name: Download Artifacts FallGuysStatsManualUpdate
        uses: actions/download-artifact@v3
        with:
          name: FallGuysStatsManualUpdate
      - name: Download Artifacts FallGuysStats
        uses: actions/download-artifact@v3
        with:
          name: FallGuysStats
      - name: Check version
        run: |
          $fileName = "Properties\AssemblyInfo.cs"
          $data = Get-Content $fileName
          echo "VERSION="+$data[12].Substring(30,3) >> $GITHUB_ENV
      - name: Commit changes
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add Properties/AssemblyInfo.cs
          git add FallGuysStats.zip
          git add FallGuysStatsManualUpdate.zip
          git commit -m "Version 1.$VERSION Update" -a
          echo "::set-output name=push::true"
        shell: bash
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: test
      - name: Release build
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v1.$VERSION.0"
          prerelease: false
          title: "Release v1.$VERSION"
          files: |
            FallGuysStats.zip
            FallGuysStatsManualUpdate.zip
